### ISSUE TITLE
Recall@1%

### ISSUE THREAD

**Issue by 2653888596** [BIT-MJY/SeqOT#10]
Hello! I admire your work very much and appreciate your contribution to the field. 
It is well-known that Recall@1 is equivalent to Top1 rate. What does Recall@1% mean in this context?

**Comment by BIT-MJY** [comment]
Thanks for your interest in our work!

If the database has 2000 reference laser scans, you should retrieve 2000x1%=20 top candidates for each query laser scan to calculate Recall@1%. Once one of the top 20 candidates is the correct loop, the numerator of Recall@1% + 1.

**Comment by 2653888596** [comment]
Thank you very much for your timely response! I searched online for a lot of information but couldn't find a definitive answer. Thank you!
