### ISSUE TITLE
Which pre-trained model is used? The code is inconsistent with the readme.

### ISSUE THREAD

**Issue by wpumain** [BIT-MJY/SeqOT#5]
The download link given by the weights of training_gem in readme and the download link given by weights in test_gem_prepare point to the same file 【pretrained_gem.pth.tar】, but the two weights in the code are set differently.
https://github.com/BIT-MJY/SeqOT/blob/1897a46ecb37c88d63e42359c1753a0c652a7fec/config/config.yml#L48
https://github.com/BIT-MJY/SeqOT/blob/1897a46ecb37c88d63e42359c1753a0c652a7fec/config/config.yml#L59

So which one should I follow?

**Comment by BIT-MJY** [comment]
The path in line 48 is for training resume. The path in line 59 is for loading the pre-trained weight while testing.

**Comment by BIT-MJY** [comment]
You can keep fine-tuning on the [pretrained_gem.pth.tar], so the link of  [amodel_gem.pth.tar] is [pretrained_gem.pth.tar].

The setup [amodel_gem.pth.tar] is just for your training resume. I think you can understand the setup after reading our code :-)

**Comment by wpumain** [comment]
I understand that [pretrained_gem.pth.tar] is trained and  [amodel_gem.pth.tar] is not trained. In essence they are the same

**Comment by BIT-MJY** [comment]
Thanks for using our code. I'm going to close this issue. If you have more questions, please feel free to reopen it.
