### ISSUE TITLE
Generating groud truth loops of NCLT dataset ​​has nothing to do with querying the dataset?

### ISSUE THREAD

**Issue by wpumain** [BIT-MJY/SeqOT#7]
https://github.com/BIT-MJY/SeqOT/blob/1897a46ecb37c88d63e42359c1753a0c652a7fec/data_prepararion/gen_ground_truth.py#L33

The poses_query data is read, but it is not used later.
https://github.com/BIT-MJY/SeqOT/blob/1897a46ecb37c88d63e42359c1753a0c652a7fec/data_prepararion/gen_ground_truth.py#L22

Generating groud truth loops of NCLT dataset ​​has nothing to do with querying the dataset?

What is the data structure of poses_database?

**Comment by BIT-MJY** [comment]
Thanks for pointing this out. This is a bug from the wrong version submitted to this repo. I have revised the [gen_ground_truth.py](https://github.com/BIT-MJY/SeqOT/blob/1897a46ecb37c88d63e42359c1753a0c652a7fec/data_prepararion/gen_ground_truth.py#L22) to generate the mapping from `poses_query` to `poses_database`. `poses_database` and `poses_query` both contain the pose matrix (4x4) of the collected trajectories.
