### ISSUE TITLE
2c × 1 × 3w？

### ISSUE THREAD

**Issue by wpumain** [BIT-MJY/SeqOT#8]
In your paper, section Ⅲ A mentions:. To this end, we  concatenate features of every three scans along the width yielding a long feature with the size of 2c × 1 × 3w and use these long features as the input to the multi-scan module.
If merged along the width direction, it should be  c × 1 × 3w？
The result of the code running is also this dimension  c × 1 × 3w。

**Comment by BIT-MJY** [comment]
The output of single-scan transformer is concatenated with its input along the channel dimension, so it is 2c.

**Comment by wpumain** [comment]
Think you
