### ISSUE TITLE
How to understand the prediction of the SeqOT model?

### ISSUE THREAD

**Issue by wpumain** [BIT-MJY/SeqOT#9]
I have carefully read your paper and code, SeqOT is indeed a very clever work.
Thank you for sharing, I was able to benefit a lot from it.
It may be because I have not been exposed to radar point cloud data processing, so my understanding of the SeqOT model is not deep enough.
May I ask you a question?

The Single-Scan Module extracts a range image (1,32,900) as (256,900,1).
MultiScan Moudle converts three range inages into a one-dimensional vector with a length of 256.
On this basis, GeM Pooling converts 20 one-dimensional vectors with a length of 256 into a one-dimensional vector with a length of 256.
In general, SeqOT converts the range image of 22 consecutive numbers into a one-dimensional vector with a length of 256.When the model predicts, match with this one-dimensional vector。Right?

Each query vector actually uses 22 rang images, and each image should have a different coordinate position. When matching, the start is also a match between each sequence of 22 images, so the database is required to contain similar sequence in query? This requires that when collecting database and query data, the driving route of the car is exactly the same as the speed of the car?At the same time, is the time interval or distance interval for collecting data the same?
If the intervals are different, for example, the first of the 22 range imageqs that make up a query sequence is collected at the starting point of the route, the second is collected after 50 meters, and the third is collected after 200 meters, so that it can be accurately Does it match?

**Comment by wpumain** [comment]
The core of the loss function is to select positive and negative samples based on overlapping values.
It is required that the 22 pictures that make up a query sequence are sorted according to the acquisition time, and do they overlap with each other?
But I don't understand the data structure of this 【more_chosen_normalized_data_120108】 file, and how to deal with it without clearing it.

**Comment by BIT-MJY** [comment]
> This requires that when collecting database and query data, the driving route of the car is exactly the same as the speed of the car?At the same time, is the time interval or distance interval for collecting data the same?

SeqOT does not use the difference matrix so it can improve the retrieval efficiency significantly. The time interval is fixed due to the LiDAR frame rate so the car speed does affect retrieval results. This is a trade-off between efficiency and performance. You can try to use sub-descriptors to generate the difference matrix to further improve the place recognition performance.

**Comment by BIT-MJY** [comment]
> But I don't understand the data structure of this 【more_chosen_normalized_data_120108】 file, and how to deal with it without clearing it.

`more_chosen_normalized_data_120108` is used to provide the training tuples. You can find how this works in our code.

**Comment by wpumain** [comment]
Think you for your help！Yes, I know how to use this file in the code. 

> more_chosen_normalized_data_120108

But how was this file made?

**Comment by BIT-MJY** [comment]
It contains triplets for training. Please see this [issue](https://github.com/BIT-MJY/SeqOT/issues/6).

**Comment by wpumain** [comment]
How is the overlap value calculated?

**Comment by BIT-MJY** [comment]
Please refer to eq 13 in our [paper](https://arxiv.org/pdf/2209.07951.pdf).

**Comment by wpumain** [comment]
Is it calculated according to this paper? 

> Delight: An Efficient Descriptor for Global Localisation Using LiDAR Intensities

Think  you

**Comment by BIT-MJY** [comment]
Please refer to eq 13 in our [paper](https://arxiv.org/pdf/2209.07951.pdf).

**Comment by wpumain** [comment]
Think you for your help!
